[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[features]
simd = ["arrow/simd"]

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies

arrow = { git="https://github.com/datafuse-extras/arrow-rs", rev = "f7d182df" }
arrow-flight = {git="https://github.com/datafuse-extras/arrow-rs", rev = "f7d182df" }
parquet = { git="https://github.com/datafuse-extras/arrow-rs", rev = "f7d182df", features = ["arrow"] }
num = "0.4"
# Crates.io dependencies

[dev-dependencies]
